name: Update Mesa.spec

on:
  schedule:
    - cron: "0 */5 * * *" # Запуск каждые 5 часа
  workflow_dispatch: # Ручной запуск

jobs:
  update-spec:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get latest commit from GitLab
      run: |
        curl -s "https://gitlab.freedesktop.org/api/v4/projects/mesa%2Fmesa/repository/commits" \
        | jq -r '.[0] | {commit: .id, date: .created_at}' > latest_commit.json
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

    - name: Update mesa.spec
      run: |
        COMMIT=$(jq -r '.commit' latest_commit.json)
        DATE=$(jq -r '.date' latest_commit.json | sed 's/T/./g' | cut -d'.' -f1 | sed 's/-//g')
        TIME=$(echo ${DATE} | cut -c9-12)
        DATE=$(echo ${DATE} | cut -c1-8)
        SHORTCOMMIT="$(echo ${COMMIT} | cut -c1-7).${DATE}.${TIME}"
        sed -i "s/^%global commit .*/%global commit ${COMMIT}/" mesa.spec
        sed -i "s/^%global shortcommit .*/%global shortcommit ${SHORTCOMMIT}/" mesa.spec

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add mesa.spec
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          COMMIT=$(jq -r '.commit' latest_commit.json)
          DATE=$(jq -r '.date' latest_commit.json | sed 's/T/./g' | cut -d'.' -f1 | sed 's/-//g')
          TIME=$(echo ${DATE} | cut -c9-12)
          DATE=$(echo ${DATE} | cut -c1-8)
          SHORTCOMMIT="$(echo ${COMMIT} | cut -c1-7).${DATE}.${TIME}"
          git commit -m "Update mesa.spec to commit ${COMMIT} (${SHORTCOMMIT})"
          git push origin HEAD:${{ github.ref_name }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up temporary files
      run: rm -f latest_commit.json
