name: Update Mesa.spec

on:
  schedule:
    - cron: "0 */5 * * *" # Запуск каждые 5 часа
  workflow_dispatch: # Ручной запуск

jobs:
  update-spec:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get latest commit from GitLab
      run: |
        curl -s "https://gitlab.freedesktop.org/api/v4/projects/mesa%2Fmesa/repository/commits" \
        | jq -r '.[0].id' > latest_commit.txt
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

    - name: Update mesa.spec
      run: |
        COMMIT=$(cat latest_commit.txt)
        SHORTCOMMIT=${COMMIT:0:7}
        sed -i "s/^%global commit .*/%global commit ${COMMIT}/" mesa.spec
        sed -i "s/^%global shortcommit .*/%global shortcommit ${SHORTCOMMIT}/" mesa.spec

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add mesa.spec
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          COMMIT=$(cat latest_commit.txt)
          SHORTCOMMIT=${COMMIT:0:7}
          git commit -m "Update mesa.spec to commit ${COMMIT} (${SHORTCOMMIT})"
          git push origin HEAD:${{ github.ref_name }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up temporary files
      run: rm -f latest_commit.txt
